# mptable: broken (not 64 bit clean)
# pnpinfo: crashes (not really useful anyway)
.if ${MK_ACPI} != "no"
SUBDIR+=	acpi
.endif
.if ${MK_BHYVE} != "no"
SUBDIR+=	bhyve
SUBDIR+=	bhyvectl
SUBDIR+=	bhyveload
.endif
.if ${MK_TOOLCHAIN} != "no"
SUBDIR+=	btxld
.endif
SUBDIR+=	cpucontrol
SUBDIR+=	lptcontrol
SUBDIR+=	mptable
SUBDIR+=	spkrtest
SUBDIR+=	zzz
