SUBDIR= \
	include \
	libibverbs \
	libibcm \
	libibumad \
	librdmacm \
	libibmad \
	complib \
	libcxgb4 \
	libmlx4 \
	libmlx5 \
	libbnxtre \
	libirdma 
SUBDIR_DEPEND_libibcm= libibverbs
SUBDIR_DEPEND_librdmacm= libibverbs
SUBDIR_DEPEND_libibmad= libibumad
SUBDIR_DEPEND_libbnxtre= libibverbs
SUBDIR_DEPEND_libcxgb4= libibverbs
SUBDIR_DEPEND_libmlx4= libibverbs
SUBDIR_DEPEND_libmlx5= libibverbs
SUBDIR_DEPEND_libirdma= libibverbs
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
