#	From: @(#)Makefile	8.2 (Berkeley) 4/20/94

# The following modules are not provided:
# 14.jove

SUBDIR=	title \
	contents \
	05.dc \
	06.bc \
	07.mail \
	18.msdiffs \
	19.memacros \
	20.meref \
	21.troff \
	22.trofftut
SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
