FILESDIR=	${SHAREDIR}/bsdconfig/media
FILES=		any.subr cdrom.subr common.subr directory.subr dos.subr \
		http.subr httpproxy.subr network.subr \
		options.subr tcpip.subr ufs.subr usb.subr wlan.subr

.include <bsd.prog.mk>
