SUBDIR= beastie \
        blank \
        daemon \
        dragon \
        fade \
        fire \
        green \
        logo \
        plasma \
        rain \
        star \
        warp

.include <bsd.subdir.mk>
