.\" Copyright (c) 1992, 1993, 1994, 1995
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)mount_nfs.8	8.3 (Berkeley) 3/29/95
.\"
.Dd November 29, 2024
.Dt MOUNT_NFS 8
.Os
.Sh NAME
.Nm mount_nfs
.Nd mount NFS file systems
.Sh SYNOPSIS
.Nm
.Op Fl 23bcdilNPsTU
.Op Fl a Ar maxreadahead
.Op Fl D Ar deadthresh
.Op Fl g Ar maxgroups
.Op Fl I Ar readdirsize
.Op Fl o Ar options
.Op Fl R Ar retrycnt
.Op Fl r Ar readsize
.Op Fl t Ar timeout
.Op Fl w Ar writesize
.Op Fl x Ar retrans
.Ar rhost : Ns Ar path node
.Sh DESCRIPTION
The
.Nm
utility calls the
.Xr nmount 2
system call to prepare and graft a remote NFS file system
.Pq Ar rhost : Ns Ar path
on to the file system tree at the point
.Ar node .
This command is normally executed by
.Xr mount 8 .
For NFSv2 and NFSv3,
it implements the mount protocol as described in RFC 1094, Appendix A and
RFC 1813, Appendix I.
For NFSv4, it uses the NFSv4 protocol as described in RFC 7530, RFC 5661 and
RFC 7862.
.Pp
By default,
.Nm
keeps retrying until the mount succeeds.
This behaviour is intended for file systems listed in
.Xr fstab 5
that are critical to the boot process.
For non-critical file systems, the
.Cm bg
and
.Cm retrycnt
options provide mechanisms to prevent the boot process from hanging
if the server is unavailable.
.Pp
If the server becomes unresponsive while an NFS file system is
mounted, any new or outstanding file operations on that file system
will hang uninterruptibly until the server comes back.
To modify this default behaviour, see the
.Cm intr
and
.Cm soft
options.
.Pp
The options are:
.Bl -tag -width indent
.It Fl o
Options are specified with a
.Fl o
flag followed by a comma separated string of options.
See the
.Xr mount 8
man page for possible options and their meanings.
The following NFS specific options are also available:
.Bl -tag -width indent
.It Cm acregmin Ns = Ns Aq Ar seconds
.It Cm acregmax Ns = Ns Aq Ar seconds
.It Cm acdirmin Ns = Ns Aq Ar seconds
.It Cm acdirmax Ns = Ns Aq Ar seconds
When attributes of files are cached, a timeout calculated to determine
whether a given cache entry has expired.
These four values determine the upper and lower bounds of the timeouts for
.Dq directory
attributes and
.Dq regular
(ie: everything else).
The default values are 3 -> 60 seconds
for regular files, and 30 -> 60 seconds for directories.
The algorithm to calculate the timeout is based on the age of the file.
The older the file,
the longer the cache is considered valid, subject to the limits above.
.It Cm actimeo Ns = Ns Aq Ar seconds
Set four cache timeouts above to specified value.
.It Cm allgssname
This option can be used along with
.Fl o Cm gssname
to specify that all operations should use the host-based initiator
credential.
This may be used for clients that run system daemons that need to
access files on the NFSv4 mounted volume.
.It Cm bg
If an initial attempt to contact the server fails, fork off a child to keep
trying the mount in the background.
Useful for
.Xr fstab 5 ,
where the file system mount is not critical to multiuser operation.
.It Cm bgnow
Like
.Cm bg ,
fork off a child to keep trying the mount in the background,
but do not attempt to mount in the foreground first.
This eliminates a
60+ second timeout when the server is not responding.
Useful for speeding up the boot process of a client when the server is
likely to be unavailable.
This is often the case for interdependent servers
such as cross-mounted servers (each of two servers is an NFS client of
the other) and for cluster nodes that must boot before the file servers.
.It Cm deadthresh Ns = Ns Aq Ar value
Set the
.Dq "dead server threshold"
to the specified number of round trip timeout intervals before a
.Dq "server not responding"
message is displayed.
.It Cm dumbtimer
Turn off the dynamic retransmit timeout estimator.
This may be useful for UDP mounts that exhibit high retry rates,
since it is possible that the dynamically estimated timeout interval is too
short.
.It Cm fg
Same as not specifying
.Cm bg .
.It Cm gssname Ns = Ns Aq Ar service-principal-name
This option can be used with the KerberosV security flavors for NFSv4 mounts
to specify the
.Dq "service-principal-name"
of a host-based entry in the default
keytab file that is used for system operations.
It allows the mount to be performed by
.Dq "root"
and avoids problems with
cached credentials for the system operations expiring.
The
.Dq "service-principal-name"
should be specified without instance or domain and is typically
.Dq "host" ,
.Dq "nfs"
or
.Dq "root" ,
although the form
.Sm off
.Aq Ar service
@
.Aq Ar fqdn
.Sm on
can also be used if the local system's
.Xr gethostname 3
value does not match the host-based principal in the keytab.
.It Cm hard
Same as not specifying
.Cm soft .
.It Cm intr
Make the mount interruptible, which implies that file system calls that
are delayed due to an unresponsive server will fail with EINTR when a
termination signal is posted for the process.
To avoid leaving file locks in an indeterminate state on the NFS
server, it is recommended that the
option be used with this option.
.It Cm maxgroups Ns = Ns Aq Ar value
Set the maximum size of the group list for the credentials to the
specified value.
This should be used for mounts on old servers that cannot handle a
group list size of 16, as specified in RFC 1057.
Try 8, if users in a lot of groups cannot get response from the mount
point.
.It Cm mountport Ns = Ns Aq Ar value
Specify the port number to be used to communicate with
.Xr mountd 8
on the NFS server.
This option allows an NFSv2 or NFSv3 mount to be done without
the need to run the
.Xr rpcbind 8
service.
This option is meaningless for an NFSv4 mount, since NFSv4
does not use the Mount protocol.
.It Cm mntudp
Force the mount protocol to use UDP transport, even for TCP NFS mounts.
(Necessary for some old
.Bx
servers.)
.It Cm nametimeo Ns = Ns Aq Ar value
Override the default of NFS_DEFAULT_NAMETIMEO for the timeout (in seconds)
for positive name cache entries.
If this is set to 0 it disables positive name caching for the mount point.
.It Cm negnametimeo Ns = Ns Aq Ar value
Override the default of NFS_DEFAULT_NEGNAMETIMEO for the timeout (in seconds)
for negative name cache entries.
If this is set to 0 it disables negative name caching for the mount point.
.It Cm nconnect Ns = Ns Aq Ar value
Specify the number of TCP connections (1-16) to be used
for an NFS Version 4, minor version 1 or 2 mount.
Multiple TCP connections can provide more client to server network
bandwidth for certain network configurations such as:
.Bd -literal
- Multiple network interfaces that are aggregated together.
- A fast network interface that uses multiple queues.
.Ed
.sp
The first TCP connection will be used for all RPCs that consist
entirely of small RPC messages.
The RPCs that can have large RPC messages (Read/Readdir/Write) are
distributed over the additional TCP connections in a round robin
fashion.
This option will result in more IP port#s being used.
This option requires the
.Cm nfsv4
option.
Note that for NFS servers such as AmazonEFS, where each new TCP
connection can connect to a different cluster that maintains lock
state separately, this option cannot be used.
.It Cm nfsv2
Use the NFS Version 2 protocol (the default is to try version 3 first
then version 2).
Note that NFS version 2 has a file size limit of 2 gigabytes.
.It Cm nfsv3
Use the NFS Version 3 protocol.
.It Cm nfsv4
Use the NFS Version 4 protocol.
This option will force the mount to use
TCP transport.
By default, the highest minor version of NFS Version 4 that is
supported by the NFS Version 4 server will be used.
See the
.Cm minorversion
option.
Make sure that all your NFS Version 4 clients have unique
values in
.Pa /etc/hostid .
.It Cm minorversion Ns = Ns Aq Ar value
Use the specified minor version for a NFS Version 4 mount,
overriding the default.
The minor versions supported are 0, 1, and 2.
This option is only meaningful when used with the
.Cm nfsv4
option.
.It Cm oneopenown
Make a minor version 1 or 2 of the NFS Version 4 protocol mount use a single
OpenOwner for all Opens.
This may be useful for a server with a very low limit on OpenOwners, such as
AmazonEFS.
It may be required when an accumulation of NFS version 4 Opens occurs,
as indicated by the
.Dq Opens
count displayed by
.Xr nfsstat 1
with the
.Fl c
and
.Fl E
command-line options.
A common case for an accumulation of Opens is a shared library within
the NFS mount that is used by several
processes, where at least one of these processes is always running.
This option cannot be used for an NFS Version 4, minor version 0 mount.
It may not work correctly when Delegations are being issued by a server,
but note that the AmazonEFS server does not issued delegations at this time.
This option is only meaningful when used with the
.Cm nfsv4
option.
.It Cm pnfs
Enable support for parallel NFS (pNFS) for minor version 1 or 2 of the
NFS Version 4 protocol.
This option is only meaningful when used with the
.Cm nfsv4
option.
.It Cm noac
Disable attribute caching.
.It Cm noconn
For UDP mount points, do not do a
.Xr connect 2 .
This must be used if the server does not reply to requests from the standard
NFS port number 2049 or replies to requests using a different IP address
(which can occur if the server is multi-homed).
Setting the
.Va vfs.nfs.nfs_ip_paranoia
sysctl to 0 will make this option the default.
.It Cm nocto
Normally, NFS clients maintain the close-to-open cache coherency.
This works by flushing at close time and checking at open time.
Checking at open time is implemented by getting attributes from
the server and purging the data cache if they do not match
attributes cached by the client.
.Pp
This option disables checking at open time.
It may improve performance for read-only mounts,
but should only be used if the data on the server changes rarely.
Be sure to understand the consequences before enabling this option.
.It Cm noinet4 , noinet6
Disables
.Dv AF_INET
or
.Dv AF_INET6
connections.
Useful for hosts that have
both an A record and an AAAA record for the same name.
.It Fl o Cm vers Ns = Ns 4
Same as
.Fl o Cm nfsv4
.El
.Sh SEE ALSO
.Xr nfsstat 1 ,
.Xr nmount 2 ,
.Xr unmount 2 ,
.Xr lagg 4 ,
.Xr nfsv4 4 ,
.Xr fstab 5 ,
.Xr gssd 8 ,
.Xr mount 8 ,
.Xr nfsd 8 ,
.Xr nfsiod 8 ,
.Xr rpcbind 8 ,
.Xr rpc.tlsclntd 8 ,
.Xr showmount 8
.Sh HISTORY
A version of the
.Nm
utility appeared in
.Bx 4.4 .
.Sh BUGS
Since NFSv4 performs open/lock operations that have their ordering strictly
enforced by the server, the options
.Cm intr
and
.Cm soft
cannot be safely used.
For NFSv4 minor version 1 or 2 mounts, the ordering is done
via session slots and the NFSv4 client now handles broken session slots
fairly well.
As such, if the
option is used along with
.Cm intr
and/or
.Cm soft ,
an NFSv4 minor version 1 or 2 mount
should work fairly well, although still not completely correctly.
For NFSv4 minor version 0 mounts,
.Cm hard
mounts without the
.Cm intr
mount option is strongly recommended.
