.PATH:	${LIBSYS_SRCTOP}/x86

SRCS+= \
	__vdso_gettc.c \
	pkru.c \
	sched_getcpu_x86.c

# We can't use sanitizer instrumentation on ifuncs called during sanitizer
# runtime startup.
.if ${MK_ASAN} != "no"
CFLAGS.__vdso_gettc.c+=-fno-sanitize=address
.endif
.if ${MK_UBSAN} != "no"
CFLAGS.__vdso_gettc.c+=-fno-sanitize=undefined
.endif
